// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kvftzyrvxzjyayaatnpb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt2ZnR6eXJ2eHpqeWF5YWF0bnBiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMDcyMzMsImV4cCI6MjA2NDg4MzIzM30.eLm-lV-E-h6MYLq5ExxalRt2RwOjLU63HYJ64nD5ifo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);